name: Publish Python Package

on:
  push:
    branches:
      - main  # This should be the branch that triggers the workflow

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x  # Replace with your Python version, e.g., "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine wheel

    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel
      working-directory: .  # Ensures the build command runs in the root directory

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*
      working-directory: .  # Ensures the upload command runs in the root directory
